# Generated by Django 5.0.6 on 2024-06-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='password', max_length=50, verbose_name='Пароль'),
        ),
    ]
