# Generated by Django 5.0.6 on 2024-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Номер счета')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('responsible_person', models.CharField(max_length=150, verbose_name='ФИО ответственного')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('inactive', 'Не в работе'), ('declined', 'Отказ'), ('closed', 'Сделка закрыта')], default='inactive', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
